### ISSUE TITLE
Transforming an existing Scopus produced CSV to match load_ieee_csv() or load_springer_csv format

### ISSUE THREAD

**Issue by colinmiller20** [NLeSC/litstudy#28]
Is there an easy way to manipulate a csv that contains pulled data from Scopus to match either the load_ieee_csv() or load_springer_csv functions? 

I saw there was an issue about 2 weeks ago that mentioned the possibility of a load_scopus_csv() equivalent function and I just want a little more clarification. 

While reading the documentation, it seems that the standard is to query Scopus directly with litstudy, but I was interested in loading existing data. 

Would something like converting my csv to ieee or springer format be feasible to do quickly, or would you recommend I query Scopus directly with litstudy until something of a load_scopus_csv() function has been implemented and circle back at that point? 

Thank you!

**Comment by stijnh** [comment]
Indeed. Currently, the only way to use Scopus is `search_scopus()` which sends a query directly to the Scopus web API.

The latest release (v1.0.4) added a new `load_csv()` function that can load any CSV file. It will work with Scopus CSV files and it will gives you common attributes (title, abstract, author, date, etc.), but it will not interpret all the column names.

Adding a `load_scopus_csv()` is still part of  future work.

**Comment by colinmiller20** [comment]
Thank you for getting back to me, that is very helpful!
