### ISSUE TITLE
ValueError: keyword grid_b when plotting histograms

### ISSUE THREAD

**Issue by semmyk-research** [NLeSC/litstudy#32]
Notice an error when calling `litstudy.plot_country_histogram(...)` and any of the other plots based on `plot_histogram`
Dug and noticed the error is because of changes in `matplotlib`.

[observed]  
All plots based on plot_histogram() throws: `ValueError: keyword grid_b is not recognized`  
Apparently, this might be due to changes in matplotlib  
        _## reproducibility: python==3.8.16, matplotlib==3.7.1_
        
        ax.grid(b=False, which='both', axis='y')
        xlabel, ylabel = ylabel, xlabel
    else:
        ax.grid(b=False, which='both', axis='x')

**Comment by stijnh** [comment]
Thanks for using litstudy and thanks for the bug report!

This has been fixed as of ee27017d1f29fd11a8bb4d0fd0e813a936dfcb5d
