### ISSUE TITLE
Having issues with refine_scopus() function (AttributeError: 'list' object has no attribute '_refine_docs')

### ISSUE THREAD

**Issue by colinmiller20** [NLeSC/litstudy#34]
Hello, I have been having issues with the refine_scopus() function and would appreciate some insight. After loading in a set of DOIs from an RIS file using 

docs_remaining = litstudy.load_ris_file('/dbfs/*****************/DOI.ris') 

I now see what type of object docs_remaining is. 

print(type(docs_remaining))
<class 'list'>

print(len(docs_remaining))
2723

and then when I go to sort which DOIs are on scopus using the refine_scopus() function, as follows: 

docs_scopus, docs_notfound = litstudy.refine_scopus(docs_remaining)

It throws an error "AttributeError: 'list' object has no attribute '_refine_docs'". 

My initial thought is that the litstudy.load_ris_file should result in the creation of a DocumentSet with all the DOIs, rather than a list. I attached my commands below to provide additional assistance. 

** For reproducibility, I am using Python 3.9.5 on a databricks 11.3 LTS (includes Apache Spark 3.3.0, Scala 2.12) instance **

Thank you so much! Please let me know if I can provide any more information. 

---- commands to reproduce----

%pip install litstudy 

import os
import sys
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sbs

plt.rcParams['figure.figsize'] = (10, 6)
sbs.set('paper')
path = os.path.abspath(os.path.join('..'))
if path not in sys.path:
    sys.path.append(path)

import litstudy

import logging
logging.getLogger().setLevel(logging.CRITICAL)

docs_remaining = litstudy.load_ris_file('/dbfs/*****************/DOI.ris')

print(type(docs_remaining))
<class 'list'>

print(len(docs_remaining))
2723

docs_scopus, docs_notfound = litstudy.refine_scopus(docs_remaining)
Creating config file at /root/.pybliometrics/config.ini with default paths...
Configuration file successfully created at /root/.pybliometrics/config.ini
For details see https://pybliometrics.rtfd.io/en/stable/configuration.html.
AttributeError: 'list' object has no attribute '_refine_docs'

**Comment by stijnh** [comment]
This has been fixed by commit ad34d85. It will be part of the next release.
