### ISSUE TITLE
loading RIS file error (Tag appears multiple times)

### ISSUE THREAD

**Issue by speanusaha** [NLeSC/litstudy#36]
![image](https://user-images.githubusercontent.com/76967509/230754647-288bcd0b-9efb-441b-ada8-a04dab3b7a09.png)

I am trying to mimic the example notebook an load ris file of full details record exported from Web of Science, but I received duplicate tags error and I cannot proceed further. Could you please let me know how can I fix this issue?

**Comment by stijnh** [comment]
Thanks for using listudy!

There are warnings, not errors. In this case, some papers have multiple "ED" (editor) and "SN" (ISBN) tags, which is not allowed by the RIS format. You can ignore these warnings. 

The RIS file will still be loaded into a `DocumentSet`. Can you confirm that `load_ris_file` still returns a document set?
