### ISSUE TITLE
Attribute Error: 'Document Set' object has no attribute 'title' when building corpus for topic modelling

### ISSUE THREAD

**Issue by SS159** [NLeSC/litstudy#37]
Would it be possible to add in 'item title' to build.corpus function for topic modelling, as currently, if you use .csv download from Scopus, title and DOI are expressed as 'Item Title' and 'Item DOI', rather than 'Item' and 'DOI'. 

Thanks!
S

**Comment by stijnh** [comment]
Hi SS159. Thanks for using litstudy!

I am not sure if I understand your question. Could you maybe show the code that you are dealing with?

You can load a CSV file using `litstudy.load_csv` which returns a `DocumentSet`.  That function automatically detects the title as "Item Title" and the DOI as "Item DOI".

You can give this `DocumentSet` to `build_corpus` as the first argument to build a corpus.

**Comment by SS159** [comment]
Hi stijnh, 

Thanks for the quick response. Sure, below is the code I'm using. I can't see where the DocumentSet is located/saved (doesn't seem to be in the working directory) - perhaps this is the problem?

![image](https://user-images.githubusercontent.com/60474063/233945583-00c92a6c-5fe2-4ac2-a4ed-5891479b38ac.png)

![image](https://user-images.githubusercontent.com/60474063/233945677-6d0d29c2-6c3b-40b0-8f53-de344ffa0250.png)

**Comment by stijnh** [comment]
The function `refine_scopus` returns two `DocumentSet`s: the documents found on Scopus and the document not found on Scopus. 

You can use it as follows:

```
docs_springer, docs_notfound  = litstudy.refine_scopus(docs_springer)
```

Here `docs_springer` is the `DocumentSet` that contains the documents found on Scopus. Give this value to `build_corpus`.

And `docs_notfound` is the `DocumentSet` that contains the documents not found on Scopus. You can ignore this value.

**Comment by SS159** [comment]
Great, I'll try this tomorrow when I'm working on the project, thanks so much for your help Stijnh! If I have any further issues I'll let you know :)

**Comment by SS159** [comment]
Thanks for getting back to me Stijnh. Unfortunately, I still can't get litstudy to build a corpus from the papers I have downloaded from Scopus, as I am finding the following error

![image](https://user-images.githubusercontent.com/60474063/234796234-9315f939-06a4-4331-9695-0f3521c9721e.png)

Note that: 1) I am using, for now, only one .csv which is from Scopus and contains 72 papers. That means that I have not merged any .csv files; 2) I have not included the function which separates documents found and not found on Scopus; 3) I note that .csv files downloaded from Scopus are not automatically saved in the format 'title' and 'doi', but rather 'item title' and 'item doi', which may also be why litstudy is unable to find attribute 'title' in the documentset (which, again, in this case is just one document 'docs_springer'). 

Thanks,

SS159

**Comment by SS159** [comment]
Hi again, just tried with the .csv from Springer instead, (which also automatically saves as 'Item Title') - can't seem to get it to work with this one either, even after changing the .csv metadata from 'Item Title' to 'Title'

![image](https://user-images.githubusercontent.com/60474063/234820709-10522fb0-1880-40b2-b8ba-d974aaab4c29.png)

**Comment by stijnh** [comment]
Hi.

Replace the line

```
docs_springer = litstudy.refine_scopus(docs_springer)
```

by

```
docs_springer, docs_notfound = litstudy.refine_scopus(docs_springer)
```
