### ISSUE TITLE
Unable to find documents based on DOI

### ISSUE THREAD

**Issue by riddhis5** [NLeSC/litstudy#46]
Hello,
When attempting to load an csv file, I am getting the, 'no document found for DOI,'  for all DOIs within the csv file. Below is an example of the error.
90%|█████████ | 451/499 [00:51<00:06,  7.57it/s]WARNING:root:no document found for DOI 10.5194/acp-22-395-2022: 

My code is as follows:
import os
import sys

path = os.path.abspath(os.path.join('..'))
if path not in sys.path:
    sys.path.append(path)

import litstudy
docs1 = litstudy.load_csv(data_path + 'data2.csv')
docs_scopus, docs_notfound = litstudy.refine_scopus(docs1)
print(len(docs_scopus), 'papers found on Scopus')
print(len(docs_notfound), 'papers were not found and were discarded')

I am unsure as to why it is not able to find the documents based on their DOIs, as they are in the correct format. Any help on this would be greatly appreciated.

**Comment by stijnh** [comment]
Thanks for you using litstudy and thanks for reporting this issue!

I was not able to reproduce your bug :-(. Could you try two things for me:

1. Can you provide the full error message? I could be something like `no document found for DOI {doi}: ...`
2. Could you test what the code `litstudy.fetch_scopus("10.5194/acp-22-395-2022")` returns?

**Comment by stijnh** [comment]
Indeed, this seems to be an issue with connecting to Scopus, not with litstudy.

Litstudy uses pybliometrics internally to communicate with Scopus. You can try to see if the following code gives an error

```
import pybliometrics
pybliometrics.scopus.AbstractRetrieval("10.1109/PACT.2015.46")
```

If this gives the same error, you can ask on the pybliometrics repository: https://github.com/pybliometrics-dev/pybliometrics
