### ISSUE TITLE
Most Cited Papers and Correlating Authors to Topic Clusters Questions

### ISSUE THREAD

**Issue by riddhis5** [NLeSC/litstudy#47]
Hi, 
Is there any way of checking which countries / authors / institutes have been citing the papers within my csv file, as I would like to find out where the papers within my csv file are most prominently being cited.
I would also be interested in knowing if there is a way to correlate authors to topic clusters, in order to see which authors are most active in each of the clusters.
Thank you!

**Comment by stijnh** [comment]
Every `Document` has a `citations` attribute that gives you a list of other papers that cited that particular document. You can use that to find out where papers are being cited. Not all data sources supported it (I believe the Scopus source does if you use `search_scopus` or `refine_scopus`).

For your second question, it is possible but it will require some Python scripting. First, train a topic model to get a topic vector per document. Next, loop over all the documents, for each document get the topic vector and loop over all the authors. You can then calculate the average over all the topic vectors for each author. It's definitely possible, but it will require some Python programming work.
