### ISSUE TITLE
TypeError: fetch_semanticscholar() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by FlashFFF** [NLeSC/litstudy#52]
When trying to use 
`docs_scopus, docs_notfound = litstudy.refine_semanticscholar(docs_bib, session=None)`
I always get the error 
`TypeError: fetch_semanticscholar() takes 1 positional argument but 2 were given`
might you please help me with this? All the rest is taken from the example.

**Comment by stijnh** [comment]
Thanks for using litstudy!

This is a bug that has been fixed, but that fix is not yet been released on pip. It will be part of the next 1.0.6 release.

You can use the latest version of litstudy by using the following command

```bash
pip install git+https://github.com/NLeSC/litstudy
```

**Comment by FlashFFF** [comment]
Thanks a lot. Has been solved
