### ISSUE TITLE
how to download data from IEEE or google scholar for a specific topics in CSV format

### ISSUE THREAD

**Issue by Haythamyounus** [NLeSC/litstudy#53]
how to download data from IEEE or google scholar for a specific topics in CSV format

**Comment by isazi** [comment]
On IEEE Xplore you can perform your search and then click the "Export" button to download a CSV file.

**Comment by Haythamyounus** [comment]
Thank you for your reply it helps me a lot, I was wondering what will be the solution for google scholar

**Comment by isazi** [comment]
Not sure about how to do it with Scholar. You can export single entries from a search in BibTex format and import them I believe.

**Comment by stijnh** [comment]
Unfortunately, Google Scholar is closed off and export or scraping the results is not made easy. As mentioned by @isazi, the only solution would be to export the result as BibTex and then use `litstudy.load_bibtex` to import the results. Alternatively, you can write down the DOIs of the articles and use `litstudy.fetch_semanticscholar` or `litstudy.fetch_crossref` to import them (see [1])

[1] https://nlesc.github.io/litstudy/api/sources.html
