### ISSUE TITLE
The "square_distances" argument of TSNE function used in calculate_embedding is deprecated

### ISSUE THREAD

**Issue by rjavierch** [NLeSC/litstudy#54]
According to this issue: https://github.com/scikit-learn/scikit-learn/issues/12401 , the `square_distance` argument of TSNE function used in calculate_embedding is deprecated since 0.28

For scikit-learn versions>=0.28 gets error:

```
File [c:\Users\user\.pyenv-win-venv\envs\psd1\lib\site-packages\litstudy\nlp.py:410](file:///C:/Users/user/.pyenv-win-venv/envs/psd1/lib/site-packages/litstudy/nlp.py:410), in calculate_embedding(corpus, rank, svd_dims, perplexity, seed)
    407 else:
    408     components = tfidf
--> 410 model = TSNE(
    411     rank, metric="cosine", square_distances=True, perplexity=perplexity, random_state=seed
    412 )
    413 return model.fit_transform(components)

TypeError: __init__() got an unexpected keyword argument 'square_distances'
```

How to reproduce an error:
Run the example notebook of the documentation by running the cell that contains:
```litstudy.plot_embedding(corpus, topic_model);```

Suggested solution: remove the `square_distance=True` argument

Willing to commit a change to the main branch: Yes

**Comment by stijnh** [comment]
Thanks for using litstudy and many thanks for creating this issue!

Indeed, it seems that the TSNE function has changed. 

> Willing to commit a change to the main branch: Yes

This would be highly appreciated. We would be willing to accept your PR. Thanks for looking into this

**Comment by rjavierch** [comment]
Hello!

I am unable to create a new branch. How can I proceed?

**Comment by stijnh** [comment]
Click the "fork" button on the main page. This will create a copy (a "fork") of the repository under you username. You can then make a new branch for this fork. When you're done, go back to the litstudy repository to create a pull request.

Here is some useful reading:
- https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request
-  https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

We are looking forward to your changes!

**Comment by rjavierch** [comment]
Thank you!, I have followed the sources you pointed and I think I have successfully created a pull request.

**Comment by stijnh** [comment]
Thanks for you contribution!
