### ISSUE TITLE
Scopus400 Error: Exceeds the maximum number allowed for the service level

### ISSUE THREAD

**Issue by SS159** [NLeSC/litstudy#61]
Using a standard Elsevier API, the maximum service level seems to be only 180 papers when using the enrich metadata function. Is this correct? The example given on LitStudy page shows around 1400 papers - any idea why this might be?

Thanks in advance, 

Sam

**Comment by stijnh** [comment]
Thanks for using LitStudy!

Mmmm, not sure what the limit is. LitStudy just passes the query directly to [pybliometrics](https://github.com/pybliometrics-dev/pybliometrics) and let's that package handle all communication with Scopus. Maybe you could ask your question on their [GitHub](https://github.com/pybliometrics-dev/pybliometrics) page

**Comment by SS159** [comment]
Sure, I'll take a look. It would seem the enforced limit is 180, which is quite a severe limitation for most query processing. 

I'll post on their page and then let you know. 

S

**Comment by FlashFFF** [comment]
Had the same error. Try using a vpn with api subscription like from your University or the like. Solved it for multiple sources.

**Comment by stijnh** [comment]
pybliometrics is tracking this in https://github.com/pybliometrics-dev/pybliometrics/issues/300
